name: mCraftManager
main: MaXoooZ\CraftManager\Base

src-namespace-prefix: MaXoooZ\CraftManager

authors:
  - MaXoooZ
  - Myma
api: [ 5.0.0 ]
version: 1.0.1

# Plugin shop
website: https://discord.gg/pocketmine
