# Plugin Shop
#
# https://discord.gg/pocketmine
# https://maxoooz.mysellix.io/

# All items you want to remove from the workbench
# You can set the meta "-1" or not set it all to include all items
delete:
  - "Wooden Pickaxe"

new:
  -
    # Organization on the 9 slots in the workbench
    shape:
      - " A "
      - " A "
      - " B "

    # All items that relate to the letters you entered just above ^
    input:
      A: "Stone"
      B: "Cobblestone"

    # Item that will be given when the player makes the craft
    output: "Diamond:1"

    # Are the crafts for the basic item removed?
    remove-old-crafts: true